In [1]:
#numpy>> numerical python
#2005 by Travis Oliphant
#before 2005 there were special mathematical tools (similar to Tora, Linga)

In [ ]:
 #as is aliasimport numpy as np

In [3]:
np.__version__

'1.23.5'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [5]:
lis = [1, 2, 3, "pwskills", 3+5j, True, 1.2] #list stores heterogenous data
type(lis)

list

In [6]:
#Numpy stored the data in a numpy array
#An array is a container/data structure used to store data of same data type>> homogenous

In [ ]:
#why numpy? already we have list, C is one of the fastest programming language after c++
#numpy is built using C>> Numpy computation is fast
#due to array>>since it stores only homogenous data, numpy array is faster
#since it stores homogenous data>> contiguous/continuous memory location
#Mathematical computation is fast

In [7]:
l = [1, 2, 3, 4, 5] #numpy array is homogenous>>all elements can be interger, float, string

In [10]:
arr = np.array(l) #numpy.ndarray>>n dimensional array

In [11]:
type(arr)

numpy.ndarray

In [13]:
arr

array([1, 2, 3, 4, 5])

In [12]:
l = [1, 2, 3, 4, 5, "Ajay"]
np.array(l)

array(['1', '2', '3', '4', '5', 'Ajay'], dtype='<U21')

In [ ]:
#array stores homogenous data

In [14]:
l = [1, 2, 3, 4, 5, 2.5]
np.array(l)

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [15]:
l = [1, 2, 3, 4, 5, 2.5, "pwskills"]
np.array(l)

array(['1', '2', '3', '4', '5', '2.5', 'pwskills'], dtype='<U32')

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr.ndim #arr has only rows

1

In [20]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [21]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr1.ndim

2

In [24]:
mat = np.matrix([1, 2, 3, 4]) #matrix is a specialised array of 2 dimension

In [25]:
type(mat)

numpy.matrix

In [26]:
mat.ndim

2

In [27]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
#To understand the dimension, see the no of opening/closing square bracket

In [28]:
np.matrix([[[1, 2], [1, 5], [3, 6]]]) #will throw error-matrix must be 2-dimensional

ValueError: matrix must be 2-dimensional

In [29]:
arr3 = np.array([[[1, 2], [1, 5], [3, 6]]])

In [30]:
arr3

array([[[1, 2],
        [1, 5],
        [3, 6]]])

In [31]:
arr3.ndim

3

In [32]:
#more ways to array
l = [1, 2, 3]
np.asarray(l) #initial function asarray to convert to an array, np.array came after this

array([1, 2, 3])

In [34]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [35]:
#asanyarray will contert the input to an ndarray, but pass ndarray subclasses through
#if something is already an array or part of array, it will simply allow to pass through it

In [36]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [37]:
mat

matrix([[1, 2, 3, 4]])

In [38]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [39]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [40]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr

array([1, 2, 3, 4, 5])

In [43]:
#accessing elements of the array
arr[0]

1

In [44]:
#array is mutable
arr[0] = 1000

In [45]:
arr

array([1000,    2,    3,    4,    5])

In [46]:
arr

array([1000,    2,    3,    4,    5])

In [48]:
#a and arr will point to same memory location, so if there is change is a or arr
#it will reflect on both

a = arr 

In [49]:
a

array([1000,    2,    3,    4,    5])

In [50]:
arr

array([1000,    2,    3,    4,    5])

In [51]:
#shallow copy>> change in one array will lead to change in another

In [54]:
a[0] = 5000

In [55]:
a

array([5000,    2,    3,    4,    5])

In [56]:
arr

array([5000,    2,    3,    4,    5])

In [57]:
arr

array([5000,    2,    3,    4,    5])

In [58]:
b = arr.copy() #deep copy>> change in one array will not reflect in another

In [59]:
b

array([5000,    2,    3,    4,    5])

In [62]:
b[0] = 11000

In [63]:
b

array([11000,     2,     3,     4,     5])

In [64]:
arr

array([5000,    2,    3,    4,    5])

In [65]:
#To create an array>> np.array, np.asarray, np.asany array

In [ ]:
#multiple approaches to generate any array

In [69]:
arr1 = np.fromfunction(lambda i, j: i==j, (3,3)) #Construct an array by executing a function over each coordinate

In [70]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [71]:
arr1.ndim

2

In [72]:
arr1.shape #shape of array

(3, 3)

In [73]:
arr1.size #no of elements in array

9

In [74]:
#True is stored as 1 and False 0 in python
True-False

1

In [76]:
arr2 = np.fromfunction(lambda i, j: i*j, (3,3))

In [77]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [78]:
arr2.ndim

2

In [79]:
arr2.shape

(3, 3)

In [80]:
arr2.size

9

In [81]:
for i in range(5):
    print(i)

0
1
2
3
4


In [82]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [85]:
(i for i in range(5))

<generator object <genexpr> at 0x7faf30183c30>

In [86]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [98]:
iterator = (i for i in range(5))

In [99]:
iterator

<generator object <genexpr> at 0x7faf300645f0>

In [100]:
np.fromiter(iterator, float) #Create a new 1-dimensional array from an iterable object.

array([0., 1., 2., 3., 4.])

In [90]:
np.fromstring('22 23 24', sep = " ")

array([22., 23., 24.])

In [102]:
np.fromstring('22 23 24', sep = " ", dtype = int) #by default is float, values inside string should be nuerical

array([22, 23, 24])

In [103]:
#for string character you have to use split
string = "Ajay, Bijay, Sanjay"
string.split(",")

['Ajay', ' Bijay', ' Sanjay']

In [104]:
np.array(string.split(","))

array(['Ajay', ' Bijay', ' Sanjay'], dtype='<U7')

In [106]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [108]:
range(10)

range(0, 10)

In [107]:
#other method of numpy >> To generate a sequence of number
np.arange(1, 10) #arange returns evenly spacified values within a given interval, by default step is 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [110]:
np.linspace(1,5, 10) #give me 10 numbers between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])